name: hire_knock
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^3.1.2
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.1
  connectivity_plus: ^5.0.1
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.12.0
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  firebase_storage: ^11.4.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loading_indicator: ^3.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.prod
    - .env.dev
    - assets/icons/
    - assets/json/
